//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace forumbar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACTIVITY_LOG
    {
        public int IdLog { get; set; }
        public Nullable<int> IdUser { get; set; }
        public string Activity { get; set; }
        public System.DateTime ActivityTime { get; set; }
    
        public virtual USER_INFO USER_INFO { get; set; }
    }
}
