//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace forumbar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GIA
    {
        public int Id { get; set; }
        public int GiaBan { get; set; }
        public System.DateTime NgayBatDau { get; set; }
        public System.DateTime NgayKetThuc { get; set; }
        public Nullable<int> MaSP { get; set; }
    
        public virtual SANPHAM SANPHAM { get; set; }
    }
}
