//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace forumbar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDER_HISTORY
    {
        public int IdHistory { get; set; }
        public Nullable<int> MaDH { get; set; }
        public string Status { get; set; }
        public System.DateTime ChangeTime { get; set; }
    
        public virtual DONHANG DONHANG { get; set; }
    }
}
