//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace forumbar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class YEUTHICH
    {
        public int IdUser { get; set; }
        public int IdBaiViet { get; set; }
        public System.DateTime ThoiGianYeuThich { get; set; }
    
        public virtual BAIVIET BAIVIET { get; set; }
        public virtual USER_INFO USER_INFO { get; set; }
    }
}
